version: '3'
services:
  yii2-rest-api-php:
    restart: "no"
    build: php/
    working_dir: /var/www/html
    ports:
      - 8888:8888
    volumes:
      - ../:/var/www/html
    depends_on:
      - yii2-rest-api-db
    networks:
      - dev

  yii2-rest-api-db:
    restart: "no"
    image: mysql:5.7
    ports:
      - 3301:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=yii2-rest-api
      - MYSQL_USER=yii2-rest-api
      - MYSQL_PASSWORD=password
    volumes:
      - yii2-rest-api:/var/lib/mysql
    labels:
      - "traefik.enable=false"
    networks:
      - dev

volumes:
  yii2-rest-api:
    driver: local
networks:
  dev: